clj/project.clj
This will update the ring libraries to their most current versions: 1.4.0
=> Updated ring versions from 1.1.8 to 1.4.0

README.md
Format "<USER>" in the text to be `code` so that the brackets are escaped.
=> Make <USER> no longer look like an HTML tag

README.md
This PR is meant to fix https://github.com/18F/cf-hello-worlds/issues/28.
I've done two things:
1. Link to docs.cloud.gov info instead of repeating info from there. This fixes the bug, because the docs.cloud.gov page has up-to-date info instead of old info.
2. Make this readme less cloud.gov-specific, so that it's easier for us to contribute this back to the CF community (https://github.com/18F/cf-hello-worlds/issues/22).
@mheadd, would you be up for taking a look at this change to see if it helps?
=> Updating readme to not repeat ourselves (and be less cloud.gov-specific)

nodejs/package.json
```
-----> Installing binaries
engines.node (package.json):  0.10.x
engines.npm (package.json):   2.x
Downloading and installing node ...
DEPENDENCY MISSING IN MANIFEST:
Unfortunately, we are either unable to resolve the dependency into
a binary and version number or the requested version or version range is not supported.
Please replace the URL with a valid link or the requested version/range
with a supported version or version range.
-----> Build failed
We're sorry this build is failing! You find more info about the nodejs buildpack here:
https://docs.cloudfoundry.org/buildpacks/node/index.html
Staging failed: Buildpack compilation step failed
FAILED
BuildpackCompileFailed
```
Looks like the node buildpack doesn't support node `0.10` anymore, let's update it!
=> Bump node to recent LTS

README.md
SuiteCRM sample app is not maintained, so we shouldn't link to it. I also toned down the description of the CF community sample apps.
=> Remove CRM example from readme

README.md, clojure/manifest.yml, dotnet-core/manifest.yml, java-see/manifest.yml, nodejs/manifest.yml, php/manifest.yml, python-flask/manifest.yml, ruby-padrino/manifest.yml, ruby-sinatra/manifest.yml
So that cloud.gov can deploy sample applications with stable urls for
canary testing.
=> Move `--random-route` flag to docs.

nodejs/manifest.yml, python-flask/manifest.yml
Top-level buildpack configuration is now deprecated.
=> Move buildpack config into applications.

pipeline.yml
Since this is an automated test that we generally only pay attention to
when there is something wrong with the platform, we should have CF_TRACE
set to true all the time in case things break. Sure it's noisy, but that
noise is helpful when we're debugging and troubleshooting issues
customer's may be experiencing.
=> Turn on CF_TRACE for these deployments

clojure/manifest.yml, dotnet-core/manifest.yml, go-hello/manifest.yml, java-see/manifest.yml, nodejs/manifest.yml, php/manifest.yml, python-flask/manifest.yml, ruby-padrino/manifest.yml, ruby-sinatra/manifest.yml
This PR has two changes: 
first, `buildpack` is deprecated in favor of `buildpacks`, so this avoids using `buildpack`
second, this adds `random-routes`, so users' routes are less likely to collide with each other.
=> Buildpack deprecation warning & random routes

dotnet-core/manifest.yml, java-see/manifest.yml, nodejs/manifest.yml, php/manifest.yml, pipeline.yml, python-flask/manifest.yml, ruby-padrino/manifest.yml, ruby-sinatra/manifest.yml
The Concourse CF resource switches on the `current_app_name` parameter to then call the autopilot zero-downtime-deploy plugin, which in turn uses an old version of the CF CLI binary.  This avoids that and removes our dependency on the plugin.  In the future may want to remove dependency on CF resource altogether unless we can convince Pivotal to maintain it.
=> Avoids call to autopilot plugin

dotnet-core/dotnet-core-hello-world.csproj, nodejs/package.json
cf 9.2 removes buildpacks that supported the old versions.
=> Update node and dotnet versions

nodejs/package.json
node 8 does not work with our buildpacks. This bumps us to node 10. I tested this in my sandbox, and it seems to work.
None
=> bump node version to one supported by this buildpack

dotnet-core/.gitignore, dotnet-core/Program.cs, dotnet-core/Startup.cs, dotnet-core/dotnet-core-hello-world.csproj
- Updated sample to use [latest version](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) of .NET runtime
- Modified structure of app files to mirror files auto created via `dotnet new web`
- Add `.gitignore` file to ignore any .NET artifacts generated locally
- None
=> Update .NET Core example to use latest version of runtime

nodejs/package.json
- Update to 14.x
- See https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.7.54
- Node v10 removed in https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.7.53
- Fixes buildpack smoke test 
none
=> Update nodejs to the default version in buildpack v1.7.54

nodejs/package.json
- Move sample nodejs min version from `14.x` to `18.x` since `14.x` was deprecated in node-js builpack
Having current hello-world apps deploying on a regular basis helps flush out platorm buildpack issues
=> Up min nodejs since 14.x was deprecated

python-flask/requirements.txt
- Fix for python-flask with error:
```
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/home/vcap/deps/0/python/lib/python3.10/site-packages/werkzeug/urls.py)
```
None
=> Patch for new version of Werkzeug

java-see/build-java-see.sh, java-see/build-java-see.yml
- Use general-task image with jdk installed for building java app
Switch to using hardened image
=> use general-task image and install jdk

dotnet-core/Startup.cs, dotnet-core/dotnet-core-hello-world.csproj
- https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.4.36 no longer supports 6.0
- Part of general platform maintenance: https://github.com/cloud-gov/private/issues/618
-
Bump codebase to supported version required by the buildpack
=> Upgrade dotnet app to use 8.0

pipeline.yml
-
From @cweibel 
> There is a concourse pipeline for deploy-python-flask which [is failing with](https://ci.fr.cloud.gov/teams/main/pipelines/test-hello-worlds/jobs/deploy-python-flask/builds/3008):
task config ‘cf-hello-worlds/python-flask/check-dependencies.yml’ not found
I can see that you removed check-dependencies.yml with https://github.com/cloud-gov/cf-hello-worlds/commit/37d70adf360c9c49613375f838a305be54da4135
Can you take a look and figure out a resolution?
-
Safe. Removed dependency on already deleted file.
=> Remove dependencies check from py-flask

nodejs/manifest-cnb.yml
- update node cnb buildpack reference URL to use docker.io to fix failing deploy
None, just fixing deployment failure
=> update node cnb buildpack reference URL to use docker.io
