cloud-gov/cf-hello-worlds

README.md

Short of #22, this will at least let people know it exists.

link to @cloudfoundry-samples

---

meteor/manifest.yml

Fixes https://github.com/18F/cf-hello-worlds/issues/16.
Neither of these properties should be necessary, as they will simply use the defaults.

simplify manifest for Meteor app

---

README.md

While we don't want to maintain these forks (or even this repository) long-term, let's at least collect links to all of the repositories in one place.

link to other example repositories

---

README.md

Addresses https://github.com/18F/cf-hello-worlds/issues/31 and fixes a few links.

Update cloud.gov info in readme

---

README.md

Steps should be consistently numbered!

Step by step instructions

---

php/manifest.yml
python-flask/manifest.yml

Let's give customers good advice 😄

Use cached buildpacks to avoid tears later.

---

nodejs/manifest.yml
pipeline.yml
ruby-sinatra/manifest.yml

So that @brittag doesn't spend time testing apps manually.

Test app deploys.

---

nodejs/manifest.yml
pipeline.yml
python-flask/manifest.yml
ruby-padrino/manifest.yml
ruby-sinatra/manifest.yml

Lower memory limits and optionally send success messages to news channel to reduce noise.

Set memory limits.

---

java-see/build.gradle
java-see/manifest.yml

spring gradle plugin latest bumped to 2.0.0 last week,
so things work w/ pin to latest 1.5.x

Fix Java build

---

README.md

Follow-up on https://github.com/18F/cf-ex-drupal/issues/19.

Add Drupal 8 example

---

.gitignore
cron-task/README.md
cron-task/index.js
cron-task/manifest.yml
cron-task/package-lock.json
cron-task/package.json

- Add a new example app that demonstrates how to deploy a one-off task
- None

Add an example demonstrating a one-off task

---

nodejs/web.js

- Updated the Node example to use more current JS language constructs like `const` and template strings.
None

Update node example to use more recent JS language constructs

---

ruby-sinatra/Gemfile.lock

- Bump rack version from 2.0.8 to 2.2.3.
Addresses vulnerability in earlier version of rack

Bump rack version to address vulnerability

---

pipeline.yml

- Updated repo path and branch
none

updating pipeline to use correct repo branch and location

---

deno/Makefile
deno/main.ts
deno/manifest.yml
pipeline.yml

- Adds a Deno "hello world" app
None, just adding a sample app

Add Deno hello world app

---

pipeline.yml

- add staging deployments - this will flex staging a little more, and the zero downtime deployment assertions assume the flask hello world is running
-
-
None

add staging deployments

---

README.md

- update broken link in README
- fixes #94 
None

replace broken link in README

---

pipeline.yml

- hardens all jobs for hello-world pipeline
-
-
hardens containers

updating for containers to use hardened container

---

pipeline.yml

fix pipeline file reference

---

static/manifest.yml

- see title
None, just changing routing strategy for example app

update static example app to use random route to avoid routing conflicts

---

pipeline.yml

- Updating to new CF Resource and hardened ones too
This enforces usage of hardened resources

Updating to new CF Resource and hardened ones too

---

python-flask/README.md
python-flask/push-python-flask.sh
python-flask/requirements.in

- Modified project by adding a requirements.in and the corresponding piptools compile command for creating the requirements.txt file
- Added a shell script to run the piptools compile command and cf push
- Added a README to tell the user how to run the shell script
None

updated project to use requirements.in

---

pipeline.yml
python-flask/check-dependencies.yml

- Updated pipeline to run the dependency check on the Python Flask app
-
-
None

update to pipeline for dependency generation

---

pipeline.yml
python-flask/check-dependencies.sh
python-flask/check-dependencies.yml

- added shell script for yml to use
- fixed typo
-
None

changed yml to use sh and fixed typo

---

python-flask/check-dependencies.sh

- Added missing bang in sh script
-
-
None

fixed typo missing bang

---

python-flask/check-dependencies.sh

- Added path so it can be found
-
-
None

added relative path to requirements.in in shell script

---

python-flask/check-dependencies.sh

- Fixed in and output paths
-
-
None

hopefully fixed path this time

---

ruby-sinatra/Gemfile
ruby-sinatra/Gemfile.lock

- bump add rackup so sinatra will work with newer versions of rack
None

bump add rackup so sinatra will work with newer versions of rack

---

pipeline.yml
python-flask/check-dependencies.yml
python-flask/manifest.yml

- Update to use hardened images
Use hardened images

update to use hardened images

---

java-see/build-java-see.sh

- This updates the jdk version downloaded for building the java app from v22 which is now archived to v21 which is an LTS version
Fixing broken test app

update jdk version

---

pipeline.yml

-
- Add cnb jobs to resources
-
Safe. Fixes already approved #169

Add cnb jobs to resources

---

pipeline.yml

- remove on_success notifications from pipeline config as they create unhelpful alert noise
None, there is no security action or benefit to having on_success notifications

remove on_success notifications from pipeline config

---

cf-cron/LICENSE
cf-cron/README.md
cf-cron/crontab
cf-cron/manifest.yml

-
-
-
Safe. Example code for demo, using well-vetting opensource code running in isolation

Adds a more generic cron example with supercronic

---

cf-cron/Makefile
cf-cron/README.md

- Addresses https://github.com/cloud-gov/product/issues/3064
- Remove binary
- Add Makefile to create it.
Safe. No binary. Has checksum. Uses SHA1SUM because that's what the maintainers use.

Address no binary AllStar finding

---

nodejs/manifest-cnb.yml

- fix nodejs paketo buildpack URL
-
-
None, just fixing deployment failure

fix nodejs paketo buildpack URL

---

python-flask-socketio/Procfile
python-flask-socketio/README.md
python-flask-socketio/client.js
python-flask-socketio/hello.py
python-flask-socketio/manifest.yml
python-flask-socketio/package-lock.json
python-flask-socketio/package.json
python-flask-socketio/requirements.txt

Customers have asked in the past about whether using web sockets is supported on cloud.gov, and if so, how to use them. This example provides at least one reference for using websockets on Cloud.gov, specifically via Python Flask and Socket.IO.
None. The code is not sensitive and the functionality demonstrated by the example is expected and supported behavior: https://docs.cloudfoundry.org/adminguide/supporting-websockets.html

Add working example of Flask + SocketIO
